version: '3.8'

services:
  db:
    image: postgres:16
    container_name: liftlogix-db
    environment:
      POSTGRES_USER: lift
      POSTGRES_PASSWORD: lift
      POSTGRES_DB: liftlogix
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lift -d liftlogix"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: liftlogix-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
